version: "3.7"

services:

  flask:
    build:
      context: ../
      dockerfile: REST_API_flask/flask/Dockerfile
    container_name: flask_Isoaligner_api
    restart: always
    environment:
      - APP_NAME=MyFlaskApp
    expose:
      - 8080

  nginx:
    build:
      context: ../
      dockerfile: REST_API_flask/nginx/Dockerfile
    container_name: nginx_Isoaligner_api
    restart: always
    ports:
      - "80:80"